import { ColourEnum } from "@/components/custom-reusable/header/desktop/side-nav/forms/helpers/color-helpers";
import { Brand, Product } from "@/lib/types/types-and-schemas";

export const dummyBrandsData: Brand[] = [
  {
    id: "1",
    name: "Superbalist",
    description: "Description for Superbalist brand.",
  },
  {
    id: "2",
    name: "Mango",
    description: "Description for Mango brand.",
  },
  {
    id: "3",
    name: "Old Khakhi",
    description: "Description for Old Khakhi brand.",
  },
  {
    id: "4",
    name: "Jack and Jones",
    description: "Description for Jack and Jones brand.",
  },
];

export const dummyProductsData: Product[] = [
  {
    id: "1",
    name: "Hargrave Ankle Boot",
    price: 500,
    priceAfterDiscount: 300,
    stockRemaining: 5,
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.Brown,
      brandId: "1",
      details: ["Ankle boot", "Lace-up design", "Leather upper", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    categories: ["Shoes"],
  },
  {
    id: "2",
    name: "Cameron Leather Boot",
    price: 800,
    priceAfterDiscount: 600,
    stockRemaining: 12,
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.Black,
      brandId: "2",
      details: ["Premium leather", "Lace-up design", "Comfort sole"],
    },
    sizes: ["7", "8", "9", "10", "11", "12"],
    categories: ["Shoes"],
  },
  {
    id: "3",
    name: "Grayson Brogue",
    price: 750,
    priceAfterDiscount: 500,
    stockRemaining: 8,
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.Tan,
      brandId: "3",
      details: ["Brogue design", "Wingtip", "Leather upper", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    categories: ["Shoes"],
  },
  {
    id: "4",
    name: "Orca Hiking Boot",
    price: 900,
    priceAfterDiscount: 900,
    stockRemaining: 10,
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.Green,
      brandId: "4",
      details: ["Waterproof", "Lace-up design", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11", "12"],
    categories: ["Shoes"],
  },
  {
    id: "5",
    name: "Jean Hiker Boots",
    price: 850,
    priceAfterDiscount: 650,
    stockRemaining: 7,
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.DarkBrown,
      brandId: "1",
      details: ["Hiking boot", "Ankle support", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    categories: ["Shoes"],
  },
  {
    id: "6",
    name: "Dylan Hiker Boot",
    price: 950,
    priceAfterDiscount: 950,
    stockRemaining: 9,
    metadata: {
      fabrication: "Faux Leather",
      colour: ColourEnum.Brown,
      brandId: "1",
      details: ["Hiking boot", "Speed laces", "Lace-up design", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    categories: ["Shoes"],
  },
  {
    id: "7",
    name: "Linen Summer Shirt",
    price: 400,
    priceAfterDiscount: 400,
    stockRemaining: 15,
    metadata: {
      fabrication: "Linen",
      colour: ColourEnum.White,
      brandId: "2",
      details: ["Comfort fit", "Breathable material"],
    },
    sizes: ["S", "M", "L", "XL"],
    categories: ["Apparels"],
  },
  {
    id: "8",
    name: "Polyester Joggers",
    price: 350,
    priceAfterDiscount: 250,
    stockRemaining: 20,
    metadata: {
      fabrication: "Polyester",
      colour: ColourEnum.Red,
      brandId: "3",
      details: ["Slim fit", "Lightweight"],
    },
    sizes: ["S", "M", "L", "XL"],
    categories: ["Apparels"],
  },
  {
    id: "9",
    name: "All-Terrain Hiking Poles",
    price: 600,
    priceAfterDiscount: 600,
    stockRemaining: 18,
    metadata: {
      fabrication: "Metal",
      colour: ColourEnum.Blue,
      brandId: "4",
      details: ["Durable", "Lightweight"],
    },
    sizes: ["One Size"],
    categories: ["Equipment"],
  },
  {
    id: "10",
    name: "Compact Camping Stove",
    price: 500,
    priceAfterDiscount: 350,
    stockRemaining: 25,
    metadata: {
      fabrication: "Stainless Steel",
      colour: ColourEnum.Black,
      brandId: "1",
      details: ["Portable", "Easy to use"],
    },
    sizes: ["One Size"],
    categories: ["Equipment"],
  },
  {
    id: "11",
    name: "Holiday Gift Set",
    price: 200,
    priceAfterDiscount: 150,
    stockRemaining: 30,
    metadata: {
      fabrication: "Various",
      colour: ColourEnum.Red,
      brandId: "2",
      details: ["Assorted items", "Festive packaging"],
    },
    sizes: ["One Size"],
    categories: ["Gift"],
  },
  {
    id: "12",
    name: "Luxury Spa Kit",
    price: 300,
    priceAfterDiscount: 300,
    stockRemaining: 22,
    metadata: {
      fabrication: "Various",
      colour: ColourEnum.White,
      brandId: "3",
      details: ["Bath salts", "Scented candles", "Essential oils"],
    },
    sizes: ["One Size"],
    categories: ["Gift"],
  },
];
