import { CollectionsEnum } from "@/lib/types/product-helpers";

import {
  MainItem1,
  MainItem2,
  MainItem3,
  MainItem4,
  MainItem5,
  Boots01,
  Boots02,
  Boots03,
  Boots04,
  Boots05,
  Linen01,
  Linen02,
  Linen03,
  Linen04,
  Linen05,
  Joggers01,
  Joggers02,
  Joggers03,
  Joggers04,
  Joggers05,
  Pole01,
  Pole02,
  Pole03,
  Pole04,
  Pole05,
  Gift01,
  Gift02,
  Gift03,
  Gift04,
  Gift05,
  Stove01,
  Stove02,
  Stove03,
  Stove04,
  Stove05,
  Beauty01,
  Beauty02,
  Beauty03,
  Beauty04,
  Beauty05,
  Sandals01,
  Sandals02,
  Sandals03,
  Sandals04,
  Sandals05,
  FlipFlop01,
  FlipFlop02,
  FlipFlop03,
  FlipFlop04,
  FlipFlop05,
} from "@/lib/product-assets";
import { ColourEnum } from "./types/colour-helpers";
import { Brand, Category, Product } from "@/lib/types/shop-schemas";

export const dummyBrandsData: Brand[] = [
  { id: "1", name: "Superbalist", description: "Description for Superbalist brand." },
  { id: "2", name: "Mango", description: "Description for Mango brand." },
  { id: "3", name: "Old Khakhi", description: "Description for Old Khakhi brand." },
  { id: "4", name: "Jack and Jones", description: "Description for Jack and Jones brand." },
];

export const dummyCategoriesData: Category[] = [
  { id: "1", name: "Boots", collection: CollectionsEnum.SHOES },
  { id: "2", name: "Sneakers", collection: CollectionsEnum.SHOES },
  { id: "3", name: "Sandals", collection: CollectionsEnum.SHOES },
  { id: "4", name: "Linen", collection: CollectionsEnum.APPARELS },
  { id: "5", name: "Joggers", collection: CollectionsEnum.APPARELS },
  { id: "6", name: "Camping", collection: CollectionsEnum.EQUIPMENT },
  { id: "7", name: "Hiking", collection: CollectionsEnum.EQUIPMENT },
  { id: "8", name: "Holiday", collection: CollectionsEnum.GIFT },
  { id: "9", name: "Luxury", collection: CollectionsEnum.GIFT },
];

export const dummyProductsData: Product[] = [
  {
    id: "3",
    name: "Grayson Brogue",
    price: 750,
    priceAfterDiscount: 500,
    stockRemaining: 4,
    images: [Boots02.src, MainItem3.src, MainItem5.src, MainItem2.src, MainItem1.src],
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.Tan,
      brandId: "3",
      details: ["Brogue design", "Wingtip", "Leather upper", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    collection: CollectionsEnum.SHOES,
    categories: ["1"], // Boots
  },
  {
    id: "13",
    name: "Summer Sandals",
    price: 200,
    priceAfterDiscount: 200,
    stockRemaining: 15,
    images: [Sandals01.src, Sandals02.src, Sandals03.src, Sandals04.src, Sandals05.src],
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.White,
      brandId: "2",
      details: ["Comfort fit", "Breathable material"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    collection: CollectionsEnum.SHOES,
    categories: ["3"], // Sandals
  },
  {
    id: "2",
    name: "Cameron Leather Boot",
    price: 800,
    priceAfterDiscount: 600,
    stockRemaining: 12,
    images: [Boots01.src, MainItem2.src, MainItem3.src, MainItem4.src, MainItem5.src],
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.Black,
      brandId: "2",
      details: ["Premium leather", "Lace-up design", "Comfort sole"],
    },
    sizes: ["7", "8", "9", "10", "11", "12"],
    collection: CollectionsEnum.SHOES,
    categories: ["1"], // Boots
  },

  {
    id: "9",
    name: "All-Terrain Hiking Poles",
    price: 600,
    priceAfterDiscount: 600,
    stockRemaining: 18,
    images: [Pole01.src, Pole02.src, Pole03.src, Pole04.src, Pole05.src],
    metadata: {
      fabrication: "Metal",
      colour: ColourEnum.Blue,
      brandId: "4",
      details: ["Durable", "Lightweight"],
    },
    sizes: ["One Size"],
    collection: CollectionsEnum.EQUIPMENT,
    categories: ["7"], // Hiking
  },
  {
    id: "4",
    name: "Orca Hiking Boot",
    price: 900,
    priceAfterDiscount: 900,
    stockRemaining: 10,
    images: [Boots03.src, MainItem4.src, MainItem3.src, MainItem1.src, MainItem5.src],
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.Green,
      brandId: "4",
      details: ["Waterproof", "Lace-up design", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11", "12"],
    collection: CollectionsEnum.SHOES,
    categories: ["1"], // Boots
  },
  {
    id: "5",
    name: "Jean Hiker Boots",
    price: 850,
    priceAfterDiscount: 650,
    stockRemaining: 4,
    images: [Boots04.src, MainItem1.src, MainItem3.src, MainItem4.src, MainItem1.src],
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.DarkBrown,
      brandId: "1",
      details: ["Hiking boot", "Ankle support", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    collection: CollectionsEnum.SHOES,
    categories: ["6"], // Camping
  },
  {
    id: "6",
    name: "Dylan Hiker Boot",
    price: 950,
    priceAfterDiscount: 950,
    stockRemaining: 9,
    images: [Boots05.src, MainItem2.src, MainItem3.src, MainItem4.src, MainItem5.src],
    metadata: {
      fabrication: "Faux Leather",
      colour: ColourEnum.Brown,
      brandId: "1",
      details: ["Hiking boot", "Speed laces", "Lace-up design", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    collection: CollectionsEnum.SHOES,
    categories: ["1"], // Boots
  },
  {
    id: "7",
    name: "Linen Summer Cloth",
    price: 400,
    priceAfterDiscount: 400,
    stockRemaining: 3,
    images: [Linen01.src, Linen02.src, Linen03.src, Linen04.src, Linen05.src],
    metadata: {
      fabrication: "Linen",
      colour: ColourEnum.White,
      brandId: "2",
      details: ["Comfort fit", "Breathable material"],
    },
    sizes: ["S", "M", "L", "XL"],
    collection: CollectionsEnum.APPARELS,
    categories: ["4"], // Linen
  },
  {
    id: "8",
    name: "Polyester Joggers",
    price: 350,
    priceAfterDiscount: 350,
    stockRemaining: 20,
    images: [Joggers01.src, Joggers02.src, Joggers03.src, Joggers04.src, Joggers05.src],
    metadata: {
      fabrication: "Polyester",
      colour: ColourEnum.Red,
      brandId: "3",
      details: ["Slim fit", "Lightweight"],
    },
    sizes: ["S", "M", "L", "XL"],
    collection: CollectionsEnum.APPARELS,
    categories: ["5"], // Joggers
  },
  {
    id: "1",
    name: "Hargrave Ankle Boot",
    price: 500,
    priceAfterDiscount: 250,
    stockRemaining: 5,
    images: [MainItem1.src, MainItem2.src, MainItem3.src, MainItem4.src, MainItem5.src],
    metadata: {
      fabrication: "Leather",
      colour: ColourEnum.Brown,
      brandId: "1",
      details: ["Ankle boot", "Lace-up design", "Leather upper", "Rubber sole"],
    },
    sizes: ["7", "8", "9", "10", "11"],
    collection: CollectionsEnum.SHOES,
    categories: ["1"], // Boots
  },
  {
    id: "10",
    name: "Compact Camping Stove",
    price: 500,
    priceAfterDiscount: 500,
    stockRemaining: 3,
    images: [Stove01.src, Stove02.src, Stove03.src, Stove04.src, Stove05.src],
    metadata: {
      fabrication: "Stainless Steel",
      colour: ColourEnum.Black,
      brandId: "1",
      details: ["Portable", "Easy to use"],
    },
    sizes: ["One Size"],
    collection: CollectionsEnum.EQUIPMENT,
    categories: ["6"], // Camping
  },
  {
    id: "11",
    name: "Holiday Gift Set",
    price: 200,
    priceAfterDiscount: 150,
    stockRemaining: 30,
    images: [Gift01.src, Gift02.src, Gift03.src, Gift04.src, Gift05.src],
    metadata: {
      fabrication: "Various",
      colour: ColourEnum.Red,
      brandId: "2",
      details: ["Assorted items", "Festive packaging"],
    },
    sizes: ["One Size"],
    collection: CollectionsEnum.GIFT,
    categories: ["8"], // Holiday
  },
  {
    id: "12",
    name: "Luxury Spa Kit",
    price: 300,
    priceAfterDiscount: 300,
    stockRemaining: 4,
    images: [Beauty02.src, Beauty01.src, Beauty03.src, Beauty04.src, Beauty05.src],
    metadata: {
      fabrication: "Various",
      colour: ColourEnum.White,
      brandId: "3",
      details: ["Bath salts", "Scented candles", "Essential oils"],
    },
    sizes: ["One Size"],
    collection: CollectionsEnum.GIFT,
    categories: ["9"], // Luxury
  },
  {
    id: "14",
    name: "Beach Sandals",
    price: 150,
    priceAfterDiscount: 60,
    stockRemaining: 10,
    images: [FlipFlop01.src, FlipFlop02.src, FlipFlop03.src, FlipFlop04.src, FlipFlop05.src],
    metadata: {
      fabrication: "Rubber",
      colour: ColourEnum.DarkBrown,
      brandId: "1",
      details: ["Waterproof", "Durable"],
    },
    sizes: ["6", "7", "8", "9", "10", "11"],
    collection: CollectionsEnum.SHOES,
    categories: ["3"], // Sandals
  },
];
